/*###############################################################################
# Module handle_admin.c (connection-fd) 
###############################################################################
*/
#include <stdio.h>
#include <string.h>
//#include "server.h"

static char*  admin_page_template=  
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"<meta charset=\"UTF-8\" />\n"
"<style type=\"text/css\">\n"
"<!--\n"
"body {\n"
"  margin: 0;\n"
"}\n"
"h1 {\n"
"  background-color:aliceblue;\n"
"  text-align:center;\n"
"  margin-top:0;\n"
"  margin-bottom:3px;\n"
"  color: #000080;\n"
"  padding:15px 5px 15px 5px;\n"
"}\n"
"h2 {\n"
"  color:#2b3856;\n"
"  padding-top:0;\n"
"  margin-top:0;\n"
"}\n"
"#menu {\n"
"  float:left;\n"
"  background-color:aliceblue;\n"
"  width:10em;\n"
"  margin: 0px 0px 10px 0px;\n"
"  padding: 0;\n"
"}\n"
"#content {\n"
"  margin-left:11em;\n"
"  background-color:white;\n"
"  margin-bottom: 10px;\n"
"  border: 1px dashed #C2DFFF;\n"
"  padding-top: 1px; \n"
"}\n"
"#foot {\n"
"  clear:both;\n"
"  text-align:center; \n"
"  background-color:aliceblue;\n"
"  padding: 4px 1px 4px 1px;  \n"
"  color: #2b3856;\n"
"}\n"
"#menu ul {\n"
"  list-style-type: none;\n"
"  padding:0;\n"
"  margin:0;\n"
"}\n"
"#menu ul li {\n"
" display: inline;\n"
" border:1px;\n"
" padding:0;\n"
" margin:0;\n"
"}\n"
"#menu ul li a {\n"
"  display: block;\n"
"  width: 8em;\n"
"  text-decoration: none;\n"
"  color:#728fce;\n"
"  border: 1px dashed #C2DFFF;\n"
"  padding: 5px 15px 5px 15px;\n"
"}\n"
"#menu ul li a:hover {\n"
"  background-color:#659ec7;\n"
"  color:white;\n"
"  font-weight:bold;\n"
"}\n"
"* html #menu ul li a {\n"
"  height: 1px;\n"
"}\n"
"-->\n"
"</style>\n"
"\n"
"<title>OpenHPC 开放高性能计算</title>\n"
"</head>\n"
"<body>\n"
"<h1>OpenHPC 开放高性能计算</h1>\n"
"<div id=\"menu\" title=\"菜单\" >\n"
"<ul>\n"
"<li><a href=\"admin_add\">添加用户</a></li>\n"
"<li><a href=\"admin_del\">删除用户</a></li>\n"
"<li><a href=\"admin_edit\">修改用户</a></li>\n"
"<li><a href=\"admin_list\">显示用户列表</a></li>\n"
"<li><a href=\"admin_view\">显示用户信息</a></li>\n"
"</ul>\n"
"</div>\n"
"<div id=\"content\" title=\"内容\" >\n"
"<h2>管理员界面</h2>\n"
"</div>\n"
"<div id=\"foot\">邮箱：<a href=\"mailto:lingweicai@sohu.com\">lingweicai@sohu.com</a> <br />\n"
" 联系电话：18600622522<br/> 京ICP备16007807号-1 </div>\n"
"</body>\n"
"</html>";

void handle_admin (int fd)
{
  write (fd,admin_page_template,strlen (admin_page_template ));
}
